---
title: "PCA plot of sequencing runs"
author: "Graeme Grimes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(SummarizedExperiment)
library(PCAtools)
library(scatterD3)
library(plotly)
```

```{r readdata}
se_files<-grep(pattern="archive",invert=T,dir("/scratch/u034/shared/wp5-rna-seq/analysis/rnaseq/",pattern = "salmon_merged_gene_counts.rds",recursive = T),value=T)

run_names<- dirname(dirname(se_files))
names(se_files)=run_names

se_lst<-se_files %>% map(~readRDS(paste0("/scratch/u034/shared/wp5-rna-seq/analysis/rnaseq/",.x)))
se<-purrr::invoke(SummarizedExperiment::cbind,se_lst)

#clean sample id
colData(se)$rnaseq_sample_id=gsub(colnames(se),pattern = "^X",replacement = "")
colData(se)$rnaseq_sample_id=gsub(colData(se)$rnaseq_sample_id,pattern="\\.",replacement = "-")
colData(se)$nfcore_run=rep(names(se_files),sapply(se_lst,ncol))

colnames(se)<-colData(se)$rnaseq_sample_id
```

## Samples

```{r showsampleinfo}
DT::datatable(as.data.frame(colData(se)))
```

## PCA plot

Peform pca using PCAtools Log2(TPM+1)

```{r pcaplot, fig.width = 12, fig.height=12}
 p<-pca(log2(assays(se)$abundance+1),removeVar=0.1)
scatterD3(p$rotated$PC1,
          p$rotated$PC2,
          col_var = colData(se)$nfcore_run,
          tooltip_text=colnames(se))

ggp<-p$rotated %>% 
  as_tibble(rownames="rnaseq_sample_id") %>%  
  mutate(nfrun=se$nfcore_run) %>% 
  ggplot(aes(x=PC1,y=PC2,label=rnaseq_sample_id))+
  geom_point(alpha=0.1)+facet_wrap(~nfrun)+
  theme_light()+
  geom_text(size=0.3)
plotly::ggplotly(ggp)
```

PCA removing dups and filtered samples

```{r pca_filtered, fig.width = 12, fig.height=12}

filtered<-read_tsv("/home/u034/ggrimes/MultiQC/filtered_rnaseq_samples_list.txt")
DT::datatable(filtered)
se_filt<-se[,!colnames(se) %in% filtered$rnaseq_sample_id]
dim(se_filt)
 p<-pca(log2(assays(se_filt)$abundance+1),removeVar=0.1)
scatterD3(p$rotated$PC1,
          p$rotated$PC2,
          col_var = colData(se_filt)$nfcore_run,
          tooltip_text=colnames(se_filt))

ggp<-p$rotated %>% 
  as_tibble(rownames="rnaseq_sample_id") %>%  
  mutate(nfrun=se_filt$nfcore_run) %>% 
  ggplot(aes(x=PC1,y=PC2,label=rnaseq_sample_id))+
  geom_point(alpha=0.1)+facet_wrap(~nfrun)+
  theme_light()+
  geom_text(size=0.3)
plotly::ggplotly(ggp)
```



## RDS Export

```{r rds_out}
saveRDS(se,"se.rds")
saveRDS(se_filt,"se_filt.rds")

```

## Session Information

```{r sessionInfo}
sessionInfo()
```
